project_id = "djmzthmmgjlkfgwkawzi"

[functions.ships-sync]
verify_jwt = false

[functions.news-sync]
verify_jwt = false

[functions.new-ships-sync]
verify_jwt = false

[functions.server-status-sync]
verify_jwt = false

[functions.cleanup-old-news]
verify_jwt = false

[functions.image-guard]
verify_jwt = false

[functions.ship-data-override]
verify_jwt = false

[functions.cleanup-raw-data]
verify_jwt = false

[functions.cleanup-sync-locks]
verify_jwt = false

[functions.test-slug-mapping]
verify_jwt = false

[functions.force-refresh-fleetyards-models]
verify_jwt = false
